# Generated by Django 2.2.5 on 2019-11-16 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('hunger', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('sanity', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('nutrition', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('perish', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Benefit',
                'verbose_name_plural': 'Benefits',
                'ordering': ['health', 'hunger', 'sanity', 'nutrition', '-perish'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('media', models.CharField(blank=True, max_length=1024, null=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('media', models.CharField(blank=True, max_length=1024, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('log', models.TextField(blank=True, default='', null=True)),
                ('benefit_cooked', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ing_benefit_cooked', to='cook.Benefit')),
                ('benefit_raw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ing_benefit_raw', to='cook.Benefit')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ing_category', to='cook.Category')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('media', models.CharField(blank=True, max_length=1024, null=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('media', models.CharField(blank=True, max_length=1024, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('cook_time', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('log', models.TextField(blank=True, default='', null=True)),
                ('benefit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_benefit', to='cook.Benefit')),
                ('ingredients', models.ManyToManyField(related_name='recipe_ingredient', to='cook.Ingredient')),
                ('store', models.ManyToManyField(related_name='recipe_store', to='cook.Store')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='store',
            field=models.ManyToManyField(related_name='ing_store', to='cook.Store'),
        ),
    ]
