# Generated by Django 2.2.5 on 2019-11-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='media',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='benefit',
            name='name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='restrictions',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
